---
- name: Ping Linux Hosts
  hosts: flogile-web
  become: true
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: rsa_id
    ansible_ssh_port: 22

  tasks:
    - name: Ping the servers
      ping:
    - name: Flogile running web container remove 
      shell: docker ps -q | xargs -I {} docker rm -f {}
    - name: Remove old Flogile web image
      shell: docker rmi $(docker images -q)
    - name: Start new Flogile web container
      shell: docker run -dit -p 80:3000 -p 443:443 {{ image_tag }}
