---
- name: Ping Linux Hosts
  hosts: flogile-web
  become: true
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: rsa_id
    ansible_ssh_port: 22

  tasks:
    - name: Ping the servers
      ping:
