name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: nc check
      run: nc -zv 3.145.105.194 22
    - name: create ssh
      run: echo "${{ secrets.AWS_SSH_PRIV_KEY }}" >rsa_id
    - name: cat 
      run: chmod 0600 rsa_id
    - name: Ansible Playbook execution 
      run: StrictHostKeyChecking=no && ansible-playbook -i iac/hosts main.yml -vvv
      
  #  - name: Build the Docker image
  #    run: docker build . --tag flogile:$(date +%y%m%d)
  #  - name:  Docker login
  #    run: docker login -u anandsreenivasan -p ${{ secrets.DOCKER_HUB_PASS }} docker.io
  #  - name: Tag the Docker image
  #    run: docker image tag flogile:$(date +%y%m%d) anandsreenivasan/flogile:$(date +%y%m%d)
  #  - name: Push the Docker image
  #    run: docker push anandsreenivasan/flogile:$(date +%y%m%d)
